import type { HIPAAUseCaseProfile, VendorPHIMetadata, HIPAAFindings } from "./types";

export interface HIPAAComplianceReport {
  report_id: string;
  generated_at: string;
  tool_version: string;

  executive_summary: {
    use_case_name: string;
    risk_classification: "HIGH" | "NEEDS_REVIEW" | "LOW";
    status: string;
    key_findings_count: number;
    vendor_count: number;
  };

  use_case_overview: {
    organization_type: string;
    ai_function: string;
    phi_involved: boolean | "unknown";
    phi_types: string[];
    input_source: string;
    output_destination: string;
    environment: string;
  };

  phi_exposure_mapping: {
    logging_behavior: string;
    retention_period_defined: boolean | "unknown";
    access_controls_documented: boolean | "unknown";
    exposure_risk_level: "high" | "medium" | "low";
  };

  vendor_analysis: {
    vendors: {
      vendor_name: string;
      role: string;
      baa_status: string;
      data_storage: string;
      logging_enabled: string;
      access_controls: string;
      risk_factors: string[];
    }[];
    overall_vendor_risk: "high" | "medium" | "low";
  };

  triggered_safeguards: {
    safeguard_id: string;
    description: string;
    category: string;
    risk_level: string;
    citations: string[];
    explanation: string;
  }[];

  risk_classification: {
    overall_risk: "HIGH" | "NEEDS_REVIEW" | "LOW";
    confidence_score: number;
    determining_factors: string[];
  };

  remediation_checklist: {
    action: string;
    priority: "high" | "medium" | "low";
    related_rule_id: string;
  }[];

  legal_references: {
    citation: string;
    description: string;
  }[];

  disclaimers: string[];
}

const TOOL_VERSION = "v0.3-demo";

const HIPAA_DISCLAIMERS = [
  "This report is generated by a deterministic rules-based system.",
  "This report does not constitute legal advice and should not be relied upon as such.",
  "Regulatory references are provided for traceability only.",
  "This assessment does not certify HIPAA compliance or non-compliance.",
  "Organizations should consult qualified legal and compliance professionals for HIPAA guidance.",
  "This tool assesses risk based on user-provided inputs; accuracy depends on input completeness.",
];

const HIPAA_CITATION_DESCRIPTIONS: Record<string, string> = {
  "45 CFR §164.308(b)(1)": "Business Associate Contracts and Other Arrangements",
  "45 CFR §164.502(e)": "Uses and Disclosures by Business Associates",
  "45 CFR §164.504(e)": "Business Associate Contract Requirements",
  "45 CFR §164.530(j)": "Documentation and Retention Requirements",
  "45 CFR §164.502(b)": "Minimum Necessary Standard",
  "45 CFR §164.312(b)": "Audit Controls",
  "45 CFR §164.308(a)(1)(ii)(D)": "Information System Activity Review",
  "45 CFR §164.312(a)(1)": "Access Control",
  "45 CFR §164.312(d)": "Person or Entity Authentication",
  "45 CFR §164.308(a)(4)": "Information Access Management",
  "45 CFR §160.103": "Definitions (Covered Entity, Business Associate)",
  "45 CFR §164.502": "Uses and Disclosures of PHI",
  "45 CFR §164.500": "Applicability",
  "45 CFR §164.504(e)(2)": "Business Associate Contract Implementation",
  "45 CFR §164.312(e)(1)": "Transmission Security",
  "45 CFR §164.530(c)": "Safeguards",
  "45 CFR §164.514": "Other Requirements Relating to Uses and Disclosures of PHI",
  "45 CFR §164.502(d)": "De-identification of PHI",
  "45 CFR §164.514(d)": "Minimum Necessary Requirements",
  "45 CFR §164.308": "Administrative Safeguards",
  "45 CFR §164.312": "Technical Safeguards",
  "45 CFR §164.308(b)(3)": "Written Contract or Other Arrangement",
};

function generateUUID(): string {
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === "x" ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

function mapRiskClassification(classification: string): "HIGH" | "NEEDS_REVIEW" | "LOW" {
  switch (classification) {
    case "High Risk":
      return "HIGH";
    case "Needs Review":
      return "NEEDS_REVIEW";
    case "Low Risk":
      return "LOW";
    default:
      return "NEEDS_REVIEW";
  }
}

function formatBoolean(value: boolean | "unknown"): string {
  if (value === true) return "Yes";
  if (value === false) return "No";
  return "Unknown";
}

function calculateExposureRisk(profile: HIPAAUseCaseProfile): "high" | "medium" | "low" {
  if (profile.phi_involved !== true) return "low";
  
  const riskFactors = [
    profile.logging_behavior === "retained" && profile.retention_period_defined !== true,
    profile.logging_behavior === "unknown",
    profile.access_controls_documented !== true,
    profile.environment === "prod",
  ].filter(Boolean).length;

  if (riskFactors >= 2) return "high";
  if (riskFactors >= 1) return "medium";
  return "low";
}

function calculateVendorRisk(vendors: VendorPHIMetadata[]): "high" | "medium" | "low" {
  if (vendors.length === 0) return "low";

  const hasNoBaa = vendors.some(v => v.baa_available === false);
  const hasUnknownBaa = vendors.some(v => v.baa_available === "unknown");
  const storesData = vendors.some(v => v.data_storage === "stored");

  if (hasNoBaa) return "high";
  if (hasUnknownBaa && storesData) return "high";
  if (hasUnknownBaa) return "medium";
  return "low";
}

function generateRemediationChecklist(findings: HIPAAFindings): HIPAAComplianceReport["remediation_checklist"] {
  const checklist: HIPAAComplianceReport["remediation_checklist"] = [];

  for (const rule of findings.triggeredRules) {
    if (rule.riskContribution === "low") continue;

    let action = "";
    let priority: "high" | "medium" | "low" = "medium";

    switch (rule.id) {
      case "hipaa_phi_no_baa":
        action = "Obtain Business Associate Agreements from all vendors processing PHI";
        priority = "high";
        break;
      case "hipaa_phi_baa_unknown":
        action = "Verify BAA status with all vendors and document findings";
        priority = "high";
        break;
      case "hipaa_phi_logging_retained":
        action = "Define and document data retention policies for PHI logs";
        priority = "high";
        break;
      case "hipaa_phi_unknown_logging":
        action = "Investigate and document logging behavior for PHI data";
        priority = "medium";
        break;
      case "hipaa_phi_no_access_controls":
        action = "Implement and document access controls for PHI systems";
        priority = "high";
        break;
      case "hipaa_phi_unknown_access_controls":
        action = "Review and document existing access control mechanisms";
        priority = "medium";
        break;
      case "hipaa_phi_prod_unknown_org":
        action = "Determine organization HIPAA classification (covered entity or business associate)";
        priority = "high";
        break;
      case "hipaa_vendor_stores_phi":
        action = "Verify vendor access controls for stored PHI data";
        priority = "medium";
        break;
      case "hipaa_vendor_logs_phi":
        action = "Review vendor logging practices and ensure PHI protection";
        priority = "medium";
        break;
      case "hipaa_phi_unknown_involvement":
        action = "Perform data classification to determine PHI involvement";
        priority = "high";
        break;
      case "hipaa_neither_entity_with_phi":
        action = "Review organization classification - processing PHI typically creates HIPAA obligations";
        priority = "high";
        break;
      case "hipaa_phi_multiple_vendors":
        action = "Audit all vendor relationships and ensure BAA coverage for each";
        priority = "medium";
        break;
      case "hipaa_phi_audio_transcription":
        action = "Implement additional safeguards for audio PHI processing";
        priority = "medium";
        break;
      case "hipaa_phi_free_text_chat":
        action = "Implement data handling controls for unstructured PHI in chat systems";
        priority = "medium";
        break;
      default:
        action = `Address compliance gap: ${rule.description}`;
        priority = rule.riskContribution === "high" ? "high" : "medium";
    }

    checklist.push({
      action,
      priority,
      related_rule_id: rule.id,
    });
  }

  return checklist.sort((a, b) => {
    const priorityOrder = { high: 0, medium: 1, low: 2 };
    return priorityOrder[a.priority] - priorityOrder[b.priority];
  });
}

export function generateHIPAAComplianceReport(
  profile: HIPAAUseCaseProfile,
  vendors: VendorPHIMetadata[],
  findings: HIPAAFindings
): HIPAAComplianceReport {
  const riskClassification = mapRiskClassification(findings.riskClassification);
  
  const determiningFactors = findings.triggeredRules
    .filter(r => r.riskContribution !== "low")
    .map(r => r.description);

  const uniqueCitations = Array.from(new Set(findings.triggeredRules.flatMap(r => r.citations)));
  
  const legalReferences = uniqueCitations.map(citation => ({
    citation,
    description: HIPAA_CITATION_DESCRIPTIONS[citation] || "HIPAA Security/Privacy Rule Reference",
  }));

  return {
    report_id: generateUUID(),
    generated_at: new Date().toISOString(),
    tool_version: TOOL_VERSION,

    executive_summary: {
      use_case_name: profile.use_case_name,
      risk_classification: riskClassification,
      status: findings.statusFlag,
      key_findings_count: findings.triggeredRules.filter(r => r.riskContribution !== "low").length,
      vendor_count: vendors.length,
    },

    use_case_overview: {
      organization_type: profile.organization_type,
      ai_function: profile.ai_function,
      phi_involved: profile.phi_involved,
      phi_types: profile.phi_types,
      input_source: profile.input_source,
      output_destination: profile.output_destination,
      environment: profile.environment,
    },

    phi_exposure_mapping: {
      logging_behavior: profile.logging_behavior,
      retention_period_defined: profile.retention_period_defined,
      access_controls_documented: profile.access_controls_documented,
      exposure_risk_level: calculateExposureRisk(profile),
    },

    vendor_analysis: {
      vendors: vendors.map(v => {
        const vendorFindings = findings.vendorAnalysis.find(va => va.vendor_name === v.vendor_name);
        return {
          vendor_name: v.vendor_name,
          role: profile.vendors_used.find(vu => vu.vendor_name === v.vendor_name)?.role || "Unknown",
          baa_status: formatBoolean(v.baa_available),
          data_storage: v.data_storage,
          logging_enabled: formatBoolean(v.logging_enabled),
          access_controls: formatBoolean(v.access_controls_documented),
          risk_factors: vendorFindings?.risk_factors || [],
        };
      }),
      overall_vendor_risk: calculateVendorRisk(vendors),
    },

    triggered_safeguards: findings.triggeredRules.map(rule => ({
      safeguard_id: rule.id,
      description: rule.description,
      category: rule.safeguard_category,
      risk_level: rule.riskContribution,
      citations: rule.citations,
      explanation: rule.explanation,
    })),

    risk_classification: {
      overall_risk: riskClassification,
      confidence_score: findings.confidenceScore,
      determining_factors: determiningFactors,
    },

    remediation_checklist: generateRemediationChecklist(findings),

    legal_references: legalReferences,

    disclaimers: HIPAA_DISCLAIMERS,
  };
}

export function exportHIPAAReportAsJSON(report: HIPAAComplianceReport, useCaseName: string): void {
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
  const sanitizedName = useCaseName.replace(/[^a-zA-Z0-9-_]/g, "_");
  const filename = `hipaa-risk-assessment_${sanitizedName}_${timestamp}.json`;

  const blob = new Blob([JSON.stringify(report, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export async function exportHIPAAReportAsPDF(report: HIPAAComplianceReport, useCaseName: string): Promise<void> {
  const { jsPDF } = await import("jspdf");
  
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
  const sanitizedName = useCaseName.replace(/[^a-zA-Z0-9-_]/g, "_");
  const filename = `hipaa-risk-assessment_${sanitizedName}_${timestamp}.pdf`;

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const marginLeft = 20;
  const marginRight = 20;
  const contentWidth = pageWidth - marginLeft - marginRight;
  let y = 20;

  const addText = (text: string, fontSize: number, fontStyle: "normal" | "bold" = "normal", color: [number, number, number] = [0, 0, 0]) => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", fontStyle);
    doc.setTextColor(color[0], color[1], color[2]);
    const lines = doc.splitTextToSize(text, contentWidth);
    doc.text(lines, marginLeft, y);
    y += lines.length * (fontSize * 0.4) + 2;
  };

  const addSpacer = (height: number) => {
    y += height;
  };

  const checkPageBreak = (requiredSpace: number) => {
    if (y + requiredSpace > 270) {
      doc.addPage();
      y = 20;
    }
  };

  addText("HIPAA AI Risk Assessment Report", 18, "bold");
  addText("Deterministic, Rules-Based Analysis", 11, "normal", [100, 100, 100]);
  addSpacer(8);

  addText("1. Executive Summary", 14, "bold");
  addText(`Use Case: ${report.executive_summary.use_case_name}`, 10);
  addText(`Risk Classification: ${report.executive_summary.risk_classification}`, 10, "bold");
  addText(`Status: ${report.executive_summary.status}`, 10);
  addText(`Key Findings: ${report.executive_summary.key_findings_count}`, 10);
  addText(`Vendors Analyzed: ${report.executive_summary.vendor_count}`, 10);
  addSpacer(6);

  checkPageBreak(40);
  addText("2. AI Use Case Overview", 14, "bold");
  addText(`Organization Type: ${report.use_case_overview.organization_type}`, 10);
  addText(`AI Function: ${report.use_case_overview.ai_function}`, 10);
  addText(`PHI Involved: ${formatBoolean(report.use_case_overview.phi_involved)}`, 10);
  if (report.use_case_overview.phi_types.length > 0) {
    addText(`PHI Types: ${report.use_case_overview.phi_types.join(", ")}`, 10);
  }
  addText(`Environment: ${report.use_case_overview.environment}`, 10);
  addText(`Input: ${report.use_case_overview.input_source}`, 10);
  addText(`Output: ${report.use_case_overview.output_destination}`, 10);
  addSpacer(6);

  checkPageBreak(40);
  addText("3. PHI Exposure Mapping", 14, "bold");
  addText(`Logging Behavior: ${report.phi_exposure_mapping.logging_behavior}`, 10);
  addText(`Retention Defined: ${formatBoolean(report.phi_exposure_mapping.retention_period_defined)}`, 10);
  addText(`Access Controls Documented: ${formatBoolean(report.phi_exposure_mapping.access_controls_documented)}`, 10);
  addText(`Exposure Risk Level: ${report.phi_exposure_mapping.exposure_risk_level.toUpperCase()}`, 10, "bold");
  addSpacer(6);

  if (report.vendor_analysis.vendors.length > 0) {
    checkPageBreak(60);
    addText("4. Vendor & BAA Analysis", 14, "bold");
    addText(`Overall Vendor Risk: ${report.vendor_analysis.overall_vendor_risk.toUpperCase()}`, 10, "bold");
    addSpacer(3);
    
    for (const vendor of report.vendor_analysis.vendors) {
      checkPageBreak(25);
      addText(`${vendor.vendor_name} (${vendor.role})`, 10, "bold");
      addText(`  BAA: ${vendor.baa_status} | Storage: ${vendor.data_storage} | Logging: ${vendor.logging_enabled}`, 9, "normal", [60, 60, 60]);
      if (vendor.risk_factors.length > 0) {
        addText(`  Risk Factors: ${vendor.risk_factors.join(", ")}`, 9, "normal", [150, 60, 60]);
      }
    }
    addSpacer(6);
  }

  checkPageBreak(50);
  addText("5. Triggered HIPAA Safeguards", 14, "bold");
  if (report.triggered_safeguards.length === 0) {
    addText("No safeguard concerns identified.", 10, "normal", [60, 60, 60]);
  } else {
    for (const safeguard of report.triggered_safeguards) {
      checkPageBreak(25);
      const riskColor: [number, number, number] = 
        safeguard.risk_level === "high" ? [180, 60, 60] : 
        safeguard.risk_level === "needs_review" ? [180, 140, 60] : [60, 140, 60];
      addText(`[${safeguard.risk_level.toUpperCase()}] ${safeguard.description}`, 10, "bold", riskColor);
      addText(`  Category: ${safeguard.category}`, 9, "normal", [60, 60, 60]);
      addText(`  ${safeguard.explanation}`, 9, "normal", [80, 80, 80]);
    }
  }
  addSpacer(6);

  checkPageBreak(40);
  addText("6. Risk Classification", 14, "bold");
  addText(`Overall Risk: ${report.risk_classification.overall_risk}`, 11, "bold");
  addText(`Confidence Score: ${(report.risk_classification.confidence_score * 100).toFixed(0)}%`, 10);
  if (report.risk_classification.determining_factors.length > 0) {
    addText("Determining Factors:", 10, "bold");
    for (const factor of report.risk_classification.determining_factors) {
      checkPageBreak(10);
      addText(`  - ${factor}`, 9, "normal", [60, 60, 60]);
    }
  }
  addSpacer(6);

  if (report.remediation_checklist.length > 0) {
    checkPageBreak(50);
    addText("7. Remediation Checklist", 14, "bold");
    for (const item of report.remediation_checklist) {
      checkPageBreak(15);
      const priorityColor: [number, number, number] = 
        item.priority === "high" ? [180, 60, 60] : 
        item.priority === "medium" ? [180, 140, 60] : [60, 60, 60];
      addText(`[${item.priority.toUpperCase()}] ${item.action}`, 9, "normal", priorityColor);
    }
    addSpacer(6);
  }

  checkPageBreak(50);
  addText("8. Legal References", 14, "bold");
  for (const ref of report.legal_references.slice(0, 10)) {
    checkPageBreak(15);
    addText(`${ref.citation}`, 9, "bold");
    addText(`  ${ref.description}`, 9, "normal", [60, 60, 60]);
  }
  if (report.legal_references.length > 10) {
    addText(`  ...and ${report.legal_references.length - 10} more references`, 9, "normal", [100, 100, 100]);
  }
  addSpacer(8);

  checkPageBreak(60);
  addText("9. Disclaimers", 14, "bold");
  for (const disclaimer of report.disclaimers) {
    checkPageBreak(12);
    addText(`- ${disclaimer}`, 9, "normal", [80, 80, 80]);
  }
  addSpacer(6);

  addText(`Report ID: ${report.report_id}`, 8, "normal", [120, 120, 120]);
  addText(`Generated: ${new Date(report.generated_at).toLocaleString()}`, 8, "normal", [120, 120, 120]);
  addText(`Tool Version: ${report.tool_version}`, 8, "normal", [120, 120, 120]);

  doc.save(filename);
}
