import type { ModelProfile, ComplianceFindings, ProviderMetadata, AppliedArticle, MetadataField } from "./types";

export interface ReportMetadataField {
  value: string | string[] | number | boolean | null;
  source: string;
  confidence: number;
}

export interface ComplianceReport {
  report_id: string;
  generated_at: string;
  tool_version: string;

  model_profile: {
    model_name: string;
    provider: string;
    use_case: string;
    user_type: string;
  };

  provider_metadata: {
    fields: Record<string, ReportMetadataField>;
    overall_confidence: number;
  } | null;

  risk_assessment: {
    classification: "HIGH" | "LIMITED" | "MINIMAL" | "NEEDS_REVIEW";
    confidence_score: number;
    triggered_rules: {
      rule_id: string;
      description: string;
      risk_level: string;
    }[];
  };

  regulatory_grounding: {
    regulation: "EU AI Act";
    references: {
      ref: string;
      title: string;
      type: "Article" | "Annex" | "Recital";
      applied_because: string;
    }[];
  };

  disclaimers: string[];
}

const TOOL_VERSION = "v0.3-demo";

const STANDARD_DISCLAIMERS = [
  "This report is generated by a deterministic rules-based system.",
  "This report does not constitute legal advice.",
  "Regulatory references are provided for traceability only.",
  "This assessment does not certify compliance or non-compliance.",
];

function generateUUID(): string {
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === "x" ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

function mapRiskClassification(classification: string): "HIGH" | "LIMITED" | "MINIMAL" | "NEEDS_REVIEW" {
  switch (classification) {
    case "High Risk":
      return "HIGH";
    case "Limited Risk":
      return "LIMITED";
    case "Minimal Risk":
      return "MINIMAL";
    default:
      return "NEEDS_REVIEW";
  }
}

function getRefType(ref: string): "Article" | "Annex" | "Recital" {
  if (ref.startsWith("Annex")) return "Annex";
  if (ref.startsWith("Recital")) return "Recital";
  return "Article";
}

function extractMetadataField<T>(field: MetadataField<T>): ReportMetadataField {
  return {
    value: field.value as string | string[] | number | boolean | null,
    source: field.source,
    confidence: field.confidence,
  };
}

export function generateComplianceReport(
  modelProfile: ModelProfile,
  findings: ComplianceFindings,
  providerMetadata: ProviderMetadata | null
): ComplianceReport {
  const report: ComplianceReport = {
    report_id: generateUUID(),
    generated_at: new Date().toISOString(),
    tool_version: TOOL_VERSION,

    model_profile: {
      model_name: modelProfile.modelName,
      provider: modelProfile.provider,
      use_case: modelProfile.useCase,
      user_type: modelProfile.userType,
    },

    provider_metadata: providerMetadata
      ? {
          fields: {
            model_id: extractMetadataField(providerMetadata.model_id),
            provider: extractMetadataField(providerMetadata.provider),
            model_family: extractMetadataField(providerMetadata.model_family),
            modality: extractMetadataField(providerMetadata.modality),
            context_window: extractMetadataField(providerMetadata.context_window),
            deployment_class: extractMetadataField(providerMetadata.deployment_class),
            owned_by: extractMetadataField(providerMetadata.owned_by),
            has_permissions: extractMetadataField(providerMetadata.has_permissions),
          },
          overall_confidence: providerMetadata.overall_confidence,
        }
      : null,

    risk_assessment: {
      classification: mapRiskClassification(findings.riskClassification),
      confidence_score: findings.confidenceScore,
      triggered_rules: findings.triggeredRules.map((rule) => ({
        rule_id: rule.id,
        description: rule.description,
        risk_level: rule.riskContribution,
      })),
    },

    regulatory_grounding: {
      regulation: "EU AI Act",
      references: (findings.appliedArticles || []).map((article: AppliedArticle) => ({
        ref: article.article,
        title: article.title,
        type: getRefType(article.article),
        applied_because: article.summary,
      })),
    },

    disclaimers: STANDARD_DISCLAIMERS,
  };

  return report;
}

export function exportReportAsJSON(report: ComplianceReport, modelName: string): void {
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
  const sanitizedModel = modelName.replace(/[^a-zA-Z0-9-_]/g, "_");
  const filename = `ai-risk-assessment_${sanitizedModel}_${timestamp}.json`;

  const blob = new Blob([JSON.stringify(report, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export async function exportReportAsPDF(report: ComplianceReport, modelName: string): Promise<void> {
  const { jsPDF } = await import("jspdf");
  
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
  const sanitizedModel = modelName.replace(/[^a-zA-Z0-9-_]/g, "_");
  const filename = `ai-risk-assessment_${sanitizedModel}_${timestamp}.pdf`;

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const marginLeft = 20;
  const marginRight = 20;
  const contentWidth = pageWidth - marginLeft - marginRight;
  let y = 20;

  const addText = (text: string, fontSize: number, fontStyle: "normal" | "bold" = "normal", color: [number, number, number] = [0, 0, 0]) => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", fontStyle);
    doc.setTextColor(color[0], color[1], color[2]);
    const lines = doc.splitTextToSize(text, contentWidth);
    doc.text(lines, marginLeft, y);
    y += lines.length * (fontSize * 0.4) + 2;
  };

  const addSpacer = (height: number) => {
    y += height;
  };

  const checkPageBreak = (requiredSpace: number) => {
    if (y + requiredSpace > 270) {
      doc.addPage();
      y = 20;
    }
  };

  addText("AI Risk Assessment Report", 18, "bold");
  addText("Deterministic, EU AI Act-grounded", 11, "normal", [100, 100, 100]);
  addSpacer(8);

  addText("Report Metadata", 14, "bold");
  addText(`Report ID: ${report.report_id}`, 10);
  addText(`Generated: ${new Date(report.generated_at).toLocaleString()}`, 10);
  addText(`Tool Version: ${report.tool_version}`, 10);
  addSpacer(6);

  checkPageBreak(40);
  addText("Model Profile", 14, "bold");
  addText(`Model: ${report.model_profile.model_name}`, 10);
  addText(`Provider: ${report.model_profile.provider}`, 10);
  addText(`Use Case: ${report.model_profile.use_case}`, 10);
  addText(`User Type: ${report.model_profile.user_type}`, 10);
  addSpacer(6);

  if (report.provider_metadata) {
    checkPageBreak(60);
    addText("Provider Metadata", 14, "bold");
    addText(`Overall Confidence: ${(report.provider_metadata.overall_confidence * 100).toFixed(0)}%`, 10);
    addSpacer(2);
    
    const fields = report.provider_metadata.fields;
    for (const [key, field] of Object.entries(fields)) {
      const displayValue = Array.isArray(field.value) ? field.value.join(", ") : String(field.value ?? "N/A");
      const displayKey = key.replace(/_/g, " ").replace(/\b\w/g, l => l.toUpperCase());
      addText(`${displayKey}: ${displayValue} (${field.source}, ${(field.confidence * 100).toFixed(0)}%)`, 9, "normal", [60, 60, 60]);
      checkPageBreak(10);
    }
    addSpacer(6);
  }

  checkPageBreak(50);
  addText("Risk Assessment", 14, "bold");
  addText(`Classification: ${report.risk_assessment.classification}`, 11, "bold");
  addText(`Confidence Score: ${(report.risk_assessment.confidence_score * 100).toFixed(0)}%`, 10);
  addSpacer(3);
  
  if (report.risk_assessment.triggered_rules.length > 0) {
    addText("Triggered Rules:", 10, "bold");
    for (const rule of report.risk_assessment.triggered_rules) {
      checkPageBreak(15);
      addText(`${rule.rule_id} [${rule.risk_level.toUpperCase()}] ${rule.description}`, 9, "normal", [60, 60, 60]);
    }
  }
  addSpacer(6);

  checkPageBreak(50);
  addText("Regulatory Grounding", 14, "bold");
  addText(`Regulation: ${report.regulatory_grounding.regulation}`, 10);
  addSpacer(3);
  
  for (const ref of report.regulatory_grounding.references) {
    checkPageBreak(20);
    addText(`${ref.ref} - ${ref.title}`, 10, "bold");
    addText(`Applied because: ${ref.applied_because}`, 9, "normal", [60, 60, 60]);
  }
  addSpacer(8);

  checkPageBreak(50);
  addText("Disclaimers", 14, "bold");
  for (const disclaimer of report.disclaimers) {
    checkPageBreak(10);
    addText(`• ${disclaimer}`, 9, "normal", [80, 80, 80]);
  }

  doc.save(filename);
}
